services:
  voicevox-engine:
    image: voicevox/voicevox_engine:cpu-latest
    container_name: voicevox-engine
    ports:
      - "50021:50021"
    restart: unless-stopped
    environment:
      - VV_CPU_NUM_THREADS=2

  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: voicevox-timebell
    ports:
      - "8080:8080"
    depends_on:
      - voicevox-engine
    restart: unless-stopped
    environment:
      - TZ=Asia/Tokyo
      - PULSE_RUNTIME_PATH=/run/user/1000/pulse
    volumes:
      - /dev/snd:/dev/snd:rw
      - /run/user/1000/pulse:/run/user/1000/pulse:rw
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    devices:
      - /dev/snd
    group_add:
      - audio
    privileged: true

# VOICEVOXエンジンのサービス設定

# アプリケーションのサービス設定
